name: OV Build MacroQuest Live Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call_build:
    uses: ./.github/workflows/ov_build_release_shared.yaml
    with:
      client_target: live
    secrets: inherit
